Add receiver
AzisabaNetwork/BallotBox pull request #7
Opened 2022-03-28 13:47 UTC by siloneco

2022-03-28 14:46 UTC, acrylic-style requested changes

2022-03-29 06:46 UTC, siloneco commented on receiver/src/main/java/net/azisaba/ballotbox/receiver/fetcher/impl/MySQLVoteFetcher.java
> +        statement.setLong(2, cal.getTime().getTime() / 1000L);
Does Votifier ( or NuVotifier ) use epoch seconds or epoch milliseconds?

2022-03-29 06:48 UTC, acrylic-style commented on receiver/src/main/java/net/azisaba/ballotbox/receiver/fetcher/impl/MySQLVoteFetcher.java
> +        statement.setLong(2, cal.getTime().getTime() / 1000L);
epoch milliseconds

2022-03-29 07:30 UTC, acrylic-style requested changes

2022-03-29 07:30 UTC, acrylic-style commented on receiver/src/main/java/net/azisaba/ballotbox/receiver/fetcher/impl/MySQLVoteFetcher.java
> +        resultSet.close();
ResultSet is automatically closed by calling `statement.close();` so this is no-op

2022-03-29 07:33 UTC, acrylic-style approved these changes

2022-03-29 07:33 UTC, merged